name: 'Terraform'

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: | 
              terraform init -reconfigure \
              -backend-config "key=${{ secrets.TF_STATE_KEY }}" \
              -backend-config "bucket=${{ secrets.TF_BUCKET_STATE }}" \
              -backend-config "dynamodb_table=${{ secrets.TF_TABLE_STATE }}" \
              -backend-config "region=${{ secrets.TF_REGION }}" \
              -backend-config "role_arn=${{ secrets.TF_ROLE_ARN }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/"master"' && github.event_name == 'push'
#        run: terraform apply -auto-approve -input=false
#      - env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}